package view;

import controller.GameController;
import javafx.scene.Scene;
import javafx.stage.Stage;
import model.GameModel;

/**
 * Manages all scene transitions.
 * Every scene uses the same 900 × 760 window size.
 */
public class ViewManager {

    /** Standard width for all scenes. */
    public static final int W = 900;
    /** Standard height for all scenes. */
    public static final int H = 760;

    /** The primary stage of the application, used to set and switch scenes throughout the application lifecycle. */
    private final Stage stage;

    /**
     * Constructor for the ViewManager, which initializes the primary stage for scene management.
     *
     * @param stage The primary stage of the application, used to set and switch scenes throughout the application lifecycle.
     */
    public ViewManager(Stage stage) {
        this.stage = stage;
    }

    // ── Main menu ─────────────────────────────────────────────────────────────

    /**
     * Shows the main menu.
     */
    public void showMainMenu() {
        MainMenuView view = new MainMenuView(this);
        stage.setScene(new Scene(view.getRoot(), W, H));
        stage.setTitle("Échecs – Menu principal");
        stage.show();
    }

    // ── Solo setup (N-Queens) ─────────────────────────────────────────────────

    /**
     * Shows the N-Queens puzzle.
     * Entry point for the "1 JOUEUR (SOLO)" button.
     */
    public void showSoloSetup() {
        NQueensView view = new NQueensView(this);
        stage.setScene(new Scene(view, W, H));
        stage.setTitle("Échecs – Problème des N-Dames");
        stage.show();
    }

    // ── 2-player setup ────────────────────────────────────────────────────────

    /**
     * Shows the game setup screen for local 2-player games.
     * Entry point for the "2 JOUEURS (LOCAL)" button.
     */
    public void showGameSetup() {
        SetupView view = new SetupView(this);
        stage.setScene(new Scene(view.getRoot(), W, H));
        stage.setTitle("Échecs – Configuration de partie");
        stage.show();
    }

    // ── Launch standard 2-player game ────────────────────────────────────────

    /**
     * Starts a standard chess game from the default starting position.
     *
     * @param whiteTime minutes for White (0 = untimed)
     * @param blackTime minutes for Black (0 = untimed)
     * @param whiteName display name for White
     * @param blackName display name for Black
     * @param fen the FEN string representing the initial board state (should be the standard starting position FEN)
     */
    public void launchGame(int whiteTime, int blackTime, String whiteName, String blackName, String fen) {
    try {
        GameModel model = (whiteTime > 0 && blackTime > 0)
            ? new GameModel(fen, whiteTime, blackTime)
            : new GameModel(fen);
        launchGameFromModel(model, whiteName, blackName);
    } catch (Exception e) {
        showErrorPopup("Impossible de lancer la partie classique", e);
    }
}

    /** 
     * Starts a standard chess game from the default starting position with no timer and default player names.
      * This is a convenience method that calls the more general launchGame method with default parameters.
     * 
     * @param wTime minutes for White (0 = untimed)
     * @param bTime minutes for Black (0 = untimed)
     */
    public void launchGame(int wTime, int bTime) {
        launchGame(wTime, bTime, "Joueur 1", "Joueur 2", "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");
    }

    // ── Launch custom-board game ──────────────────────────────────────────────

    /**
     * Starts a chess game from a custom FEN (no timer, default player names).
     * The FEN must contain exactly one white king and one black king; the
     * board editor in {@link SetupView} enforces this before calling here.
     *
     * @param fen valid FEN string generated by the board editor
     */
    public void launchCustomGame(String fen) {
        try {
            GameModel model = new GameModel(fen);
            launchGameFromModel(model, "Joueur 1", "Joueur 2");
        } catch (Exception e) {
            showErrorPopup("Impossible de lancer la partie personnalisée", e);
        }
    }

    // ── Shared game-launch logic ──────────────────────────────────────────────

    /**
     * Launches a game from a given model and player names.
     *
     * @param model The game model to use.
     * @param whiteName The name of the white player.
     * @param blackName The name of the black player.
     */
    private void launchGameFromModel(GameModel model, String whiteName, String blackName) {
        GameView view = new GameView(this);
        view.setPlayerNames(whiteName, blackName);

        GameController controller = new GameController(model, view);
        controller.init();

        Scene scene = new Scene(view, W, H);
        scene.addEventFilter(javafx.scene.input.KeyEvent.KEY_PRESSED, ev -> {
            if (ev.getCode() == javafx.scene.input.KeyCode.ESCAPE) {
                if (view.isPauseMenuVisible()) {
                    view.setPauseMenuVisible(false);
                    controller.onSquareSelected(null);
                } else {
                    view.setPauseMenuVisible(true);
                    controller.onPauseRequested();
                }
                ev.consume();
            }
        });

        stage.setScene(scene);
        stage.setTitle("Échecs – " + whiteName + " vs " + blackName);
        stage.show();
    }


    // ── Utility ───────────────────────────────────────────────────────────────

    /**
     * Displays an error popup with the given context and exception details.
     *
     * @param context The context of the error.
     * @param e The exception that occurred.
     */
    private void showErrorPopup(String context, Exception e) {
        javafx.scene.control.Alert alert = new javafx.scene.control.Alert(javafx.scene.control.Alert.AlertType.ERROR);
        alert.setTitle("Erreur");
        alert.setHeaderText(context);
        alert.setContentText(e.getMessage());
        alert.showAndWait();
    }
}